name: Release

on:
  push:
    branches: [ master, next, beta ]

jobs:
  build-release:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./js-sdk

    strategy:
      matrix:
        node: [ '14.x' ]
        os: [ ubuntu-latest ]

    env:
      CI: 1 # prevents extra Cypress installation progress messages
      HUSKY: 0 # disables husky hooks

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "js-sdk"

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
        with:
          working-directory: ./js-sdk

      - name: Build
        run: make build
        env:
          SKIP_INSTALL: 1 # install with cache was done already

      - name: Release
        run: make release
        env:
          ENVIRONMENT: prod
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}

      # - name: Slack Deploy / Release Alert
      #   uses: 8398a7/action-slack@v3
      #   if: always()
      #   with:
      #     status: ${{ job.status }}
      #     channel: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
      #     fields: 'repo,commit,message,workflow,job'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}