name: Release

on:
  push:
    branches: [master, release-sdk]

jobs:
  release-sdk:
    runs-on: 'ubuntu-latest'

    env:
      HUSKY: 0 # disables husky hooks

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.*

      - name: Build
        run: make build

      - name: Release
        run: make release
        env:
          ENVIRONMENT: prod
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}

      - id: login-to-gcp
        name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: psqpayments-shd-operations
          workload_identity_provider: projects/6883124133/locations/global/workloadIdentityPools/credova/providers/credova-github

      - name: Release CDN
        run: make release-cdn
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.JS_AWS_ACCESS_KEY }}
          AWS_REGION: us-east-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JS_AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: dev
          IS_PR_WORKFLOW: true
